apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: orgoveggies/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: FRONTEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: FRONTEND_PORT
            - name: NGINX_BACKEND_HOST
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NGINX_BACKEND_HOST
            - name: NGINX_BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NGINX_BACKEND_PORT
